main: aliuly\itemcasepe\Main
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
load: POSTWORLD

name: ItemCasePE
description: An implementation of Bukkit's ItemCase
version: 1.1.0
author: aliuly
authors: [gamesukimanIRS]
website: https://github.com/gamesukimanIRS/ItemCasePE

commands:
  itemcase:
    description: ItemCase management command
    usage: "/itemcase [add|cancel|respawn]"
    aliases: [ic]
    permission: itemcase.cmd

permissions:
  itemcase.cmd:
    default: op
    description: "allow players access to the itemcase command"
